### PR TITLE
Fix null HTTP_COOKIE, rtrim first param must be string

### PR DESCRIPTION
**Pull request by pistej**
@gnutix small fix, php 8.1 compatibility

### CODE REVIEW

**Comment by FilipBenco** [comment]
@gnutix sorry to disturb you, we are trying to upgrade one of our slim apps to newer PHP version. Could you give us maybe just some ETA, when you'll have time to look at this?

We will then plan our work accordingly :)

**Comment by gnutix** [comment]
Looks good. I'll refresh the tag beginning of the afternoon. However, for as long as you're still testing this package with PHP 8.1, you might want to use `2.x@dev-master` so that as soon as PRs are merged, you can use them.

**Comment by pistej** [comment]
@gnutix thanks

**Comment by gnutix** [comment]
@pistej tag updated.

**Pull request merged**
